name: Deploy Helm Chart

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment on which to deploy (dev|staging|prod)"
        type: choice
        required: false
        options:
          - dev
          - staging
          - prod
        default: dev

env:
  CLUSTER_ID: "cbf52d659db8b4fb1b11d4646884f4a1a"
  DEPLOY_NAME: demo
  IMAGE_REPO: nginx
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64]

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Install Helm
      run: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
    
    - uses: aliyun/ack-set-context@v1
      with:
        access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        cluster-id: ${{ env.CLUSTER_ID }}

    - name: Setup kubeconfig
      run: |
         # 获取 Kubeconfig
         mkdir -p $HOME/.kube
         aliyun cs GET /k8s/${{ env.CLUSTER_ID }}/user_config | jq -r '.config' > $HOME/.kube/config

    - name: Install kubectl
      run: |
        sudo curl -LO https://kubernetes-release.pek3b.qingstor.com/release/v1.21.4/bin/linux/amd64/kubectl
        sudo chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Deploy with Helm to ACK
      run: |
        # 使用 Helm 部署
        helm upgrade --install ${{ env.DEPLOY_NAME }} ./.github/helm -f ./github/helm/templates/dev-${{ github.event.inputs.option }}.yaml \
           #--set image.repository=registry.cn-beijing.aliyuncs.com/dfs-demo/net-core \
           --set image.repository=${{ env.IMAGE_REPO }} \
           --set image.tag=${{ env.IMAGE_TAG }}
